channels:
- pytorch
- conda-forge
- soumith
- defaults
dependencies:
- appnope=0.1.4
- asttokens=2.4.1
- brotli-python=1.1.0
- bzip2=1.0.8
- ca-certificates=2024.8.30
- certifi=2024.8.30
- cffi=1.17.1
- charset-normalizer=3.3.2
- comm=0.2.2
- debugpy=1.8.5
- decorator=5.1.1
- exceptiongroup=1.2.2
- executing=2.1.0
- freetype=2.12.1
- gmp=6.3.0
- gmpy2=2.1.5
- h2=4.1.0
- hpack=4.0.0
- hyperframe=6.0.1
- idna=3.10
- importlib-metadata=8.5.0
- importlib_metadata=8.5.0
- ipykernel=6.29.5
- ipython=8.27.0
- jedi=0.19.1
- jinja2=3.1.4
- jupyter_client=8.6.2
- jupyter_core=5.7.2
- krb5=1.21.3
- lcms2=2.16
- lerc=4.0.0
- libblas=3.9.0
- libcblas=3.9.0
- libcxx=18.1.8
- libdeflate=1.21
- libedit=3.1.20191231
- libexpat=2.6.3
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=13.2.0
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- libopenblas=0.3.24
- libpng=1.6.44
- libsodium=1.0.20
- libsqlite=3.46.1
- libtiff=4.7.0
- libwebp-base=1.4.0
- libxcb=1.16
- libzlib=1.3.1
- llvm-openmp=15.0.7
- markupsafe=2.1.5
- matplotlib-inline=0.1.7
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- ncurses=6.5
- nest-asyncio=1.6.0
- networkx=3.3
- numpy=2.1.1
- openjpeg=2.5.2
- openssl=3.3.2
- packaging=24.1
- parso=0.8.4
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=10.4.0
- pip=24.2
- platformdirs=4.3.2
- prompt-toolkit=3.0.47
- psutil=6.0.0
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.3
- pycparser=2.22
- pygments=2.18.0
- pysocks=1.7.1
- python=3.12.6
- python-dateutil=2.9.0
- python_abi=3.12
- pytorch=2.4.1
- pyyaml=6.0.2
- pyzmq=26.2.0
- readline=8.2
- requests=2.32.3
- setuptools=73.0.1
- six=1.16.0
- stack_data=0.6.2
- sympy=1.13.2
- tk=8.6.13
- tornado=6.4.1
- traitlets=5.14.3
- typing_extensions=4.12.2
- tzdata=2024a
- urllib3=2.2.3
- wcwidth=0.2.13
- wheel=0.44.0
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- yaml=0.2.5
- zeromq=4.3.5
- zipp=3.20.1
- zstandard=0.23.0
- zstd=1.5.6
- pip:
  - filelock==3.16.0
  - fsspec==2024.9.0
  - iniconfig==2.0.0
  - pluggy==1.5.0
  - pytest==8.3.3
  - torch==2.4.1
  - torchaudio==2.4.1
  - torchvision==0.19.1
name: transformer_env
